---
- appliance_access_consolecli_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.appliance_info) instead.
- appliance_access_consolecli:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.vcsa_settings) instead.
- appliance_access_dcui_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.appliance_info) instead.
- appliance_access_dcui:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.vcsa_settings) instead.
- appliance_access_shell_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.appliance_info) instead.
- appliance_access_shell:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.vcsa_settings) instead.
- appliance_access_ssh_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.appliance_info) instead.
- appliance_access_ssh:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.vcsa_settings) instead.
- appliance_health_applmgmt_info:
- appliance_health_database_info:
- appliance_health_databasestorage_info:
- appliance_health_load_info:
- appliance_health_mem_info:
- appliance_health_softwarepackages_info:
- appliance_health_storage_info:
- appliance_health_swap_info:
- appliance_health_system_info:
# appliance_health_system_lastcheck
#   returns an err500
- appliance_infraprofile_configs_info:
- appliance_infraprofile_configs:
- appliance_localaccounts_globalpolicy_info:
- appliance_localaccounts_globalpolicy:
- appliance_localaccounts_info:
# appliance_localaccounts
#   we cannot create a functional local account. The 7.0.2 API
#   creates an account without any UNIX groups.
#   In addition, only the first role of the list is actually
#   attached to the new account.
- appliance_monitoring_info:
- appliance_monitoring_query:
- appliance_networking_dns_domains_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.appliance_info) instead.
- appliance_networking_dns_domains:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.vcsa_settings) instead.
- appliance_networking_dns_hostname_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.appliance_info) instead.
- appliance_networking_dns_hostname:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.vcsa_settings) instead.
- appliance_networking_dns_servers_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.appliance_info) instead.
- appliance_networking_dns_servers:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.vcsa_settings) instead.
- appliance_networking_firewall_inbound_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.appliance_info) instead.
- appliance_networking_firewall_inbound:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.vcsa_settings) instead.
- appliance_networking_info:
- appliance_networking_interfaces_info:
- appliance_networking_interfaces_ipv4_info:
- appliance_networking_interfaces_ipv4:
- appliance_networking_interfaces_ipv6_info:
- appliance_networking_interfaces_ipv6:
- appliance_networking_noproxy_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.appliance_info) instead.
- appliance_networking_noproxy:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.vcsa_settings) instead.
- appliance_networking_proxy_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.appliance_info) instead.
- appliance_networking_proxy:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.vcsa_settings) instead.
- appliance_networking:
- appliance_ntp_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.appliance_info) instead.
- appliance_ntp:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.vcsa_settings) instead.
- appliance_services_info:
- appliance_services:
- appliance_shutdown_info:
- appliance_shutdown:
- appliance_system_globalfips_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.appliance_info) instead.
- appliance_system_globalfips:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.vcsa_settings) instead.
- appliance_system_storage_info:
- appliance_system_storage:
- appliance_system_time_info:
- appliance_system_time_timezone_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.appliance_info) instead.
- appliance_system_time_timezone:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.vcsa_settings) instead.
- appliance_system_version_info:
- appliance_timesync_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.appliance_info) instead.
- appliance_timesync:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.vcsa_settings) instead.
- appliance_update_info:
- appliance_vmon_service_info:
- appliance_vmon_service:
- content_library_item_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.content_library_item_info) instead.
- content_library_info:
- content_library_subscriptions_info:
- content_locallibrary_info:
- content_locallibrary:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.local_content_library) instead.
- content_subscribedlibrary_info:
- content_subscribedlibrary:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.subscribed_content_library) instead.
- content_configuration_info:
- content_configuration:
- vcenter_cluster_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.cluster_info) instead.
- vcenter_datacenter_info:
- vcenter_datacenter:
- vcenter_datastore_info:
- vcenter_folder_info:
- vcenter_host_info:
- vcenter_host:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.esxi_host) instead.
- vcenter_info:
- vcenter_network_info:
- vcenter_ovf_libraryitem:
    documentation:
      description: This operation creates a library item in content library whose content is an OVF package derived from a source virtual machine or virtual appliance, using the supplied create specification. For an existing library item whose content is updated by this operation, the original content is overwritten. Meta data such as name and description is not updated for the existing library item. PLease see the examples for a workaround if you need to update the description.
- vcenter_resourcepool_info:
- vcenter_resourcepool:
- vcenter_storage_policies_info:
- vcenter_storage_profile_info:
- vcenter_vm_guest_customization:
    documentation:
      short_description: Applies a customization specification on the virtual machine
      description: Applies a customization specification on the virtual machine in {@param.name vm}. The actual customization happens inside the guest when the virtual machine is powered on. If there is a pending customization for the virtual machine and a new one is set, then the existing customization setting will be overwritten with the new settings.
- vcenter_vm_guest_filesystem_directories:
- vcenter_vm_guest_identity_info:
- vcenter_vm_guest_localfilesystem_info:
- vcenter_vm_guest_networking_info:
- vcenter_vm_guest_networking_interfaces_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.vm_portgroup_info) instead.
- vcenter_vm_guest_networking_routes_info:
- vcenter_vm_guest_operations_info:
- vcenter_vm_guest_power_info:
- vcenter_vm_guest_power:
    documentation:
      short_description: Issues a request to the guest operating system asking it to perform a soft shutdown, standby (suspend) or soft reboot
      seealso:
        - module: vmware.vmware_rest.vcenter_vm_power
          description: A module to boot, hard shutdown and hard reset guest
      description: Issues a request to the guest operating system asking it to perform a soft shutdown, standby (suspend) or soft reboot. This request returns immediately and does not wait for the guest operating.
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.vm_powerstate) instead.
- vcenter_vm_hardware_adapter_sata_info:
- vcenter_vm_hardware_adapter_sata:
- vcenter_vm_hardware_adapter_scsi_info:
- vcenter_vm_hardware_adapter_scsi:
- vcenter_vm_hardware_boot_device_info:
- vcenter_vm_hardware_boot_device:
- vcenter_vm_hardware_boot_info:
- vcenter_vm_hardware_boot:
- vcenter_vm_hardware_cdrom_info:
- vcenter_vm_hardware_cdrom:
- vcenter_vm_hardware_cpu_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.vm_resource_info) instead.
- vcenter_vm_hardware_cpu:
- vcenter_vm_hardware_disk_info:
- vcenter_vm_hardware_disk:
    documentation:
      short_description: Adds a thin provisioned virtual disk to the virtual machine
      description: Adds a virtual disk to the virtual machine. The disk (provision) type is always 'thin'. While adding the virtual disk, a new VMDK file may be created or an existing VMDK file may be used to back the virtual disk.
- vcenter_vm_hardware_ethernet_info:
- vcenter_vm_hardware_ethernet:
- vcenter_vm_hardware_floppy_info:
- vcenter_vm_hardware_floppy:
- vcenter_vm_hardware_info:
- vcenter_vm_hardware_memory_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.vm_resource_info) instead.
- vcenter_vm_hardware_memory:
- vcenter_vm_hardware_parallel_info:
- vcenter_vm_hardware_parallel:
- vcenter_vm_hardware:
- vcenter_vm_hardware_serial_info:
- vcenter_vm_hardware_serial:
- vcenter_vm_info:
- vcenter_vm_libraryitem_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.content_library_item_info) instead.
- vcenter_vm_power_info:
- vcenter_vm_power:
    documentation:
      short_description: Operate a boot, hard shutdown, hard reset or hard suspend on a guest.
      seealso:
        - module: vmware.vmware_rest.vcenter_vm_guest_power
          description: Issues a request to the guest operating system asking it to perform a soft shutdown, standby (suspend) or soft reboot
      description: Ask the vCenter to boot, force shutdown or force reset a guest.
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.vm_powerstate) instead.
- vcenter_vm:
- vcenter_vm_storage_policy_compliance_info:
- vcenter_vm_storage_policy_compliance:
- vcenter_vm_storage_policy_info:
- vcenter_vm_storage_policy:
- vcenter_vm_tools_info:
- vcenter_vm_tools_installer_info:
- vcenter_vm_tools_installer:
- vcenter_vm_tools:
- vcenter_vmtemplate_libraryitems_info:
    documentation:
      deprecated:
        removed_in: 5.0.0
        why: This module has been moved to the L(new vmware.vmware collection,https://forum.ansible.com/t/5880)
        alternative: Use M(vmware.vmware.content_library_items_info) instead.
- vcenter_vmtemplate_libraryitems:
